---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

resources:
  requests:
    cpu: 1000
    memory: 1024Mi

environment:
  OCI_IMAGE_REPO: quay.io/ukhomeofficedigital/alpine

steps:
- name: build
  pull: Always
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  resources:
    limits:
      cpu: 1000
      memory: 1024Mi
  commands:
  # wait for docker service to be up before running docker build
  - n=0; while [ "$n" -lt 60 ] && [ ! "$(docker stats --no-stream)" ]; do n=$(( n + 1 )); sleep 1; done
  - docker build --build-arg ALPINE_TAG=$$(cat .alpine_version) -t "$${OCI_IMAGE_REPO}:$$(cat .alpine_version)" . --no-cache
  - docker tag "$${OCI_IMAGE_REPO}:$$(cat .alpine_version)" "$${OCI_IMAGE_REPO}:${DRONE_COMMIT_SHA}"
  when:
    event:
      include:
      - push
      - pull_request
      exclude:
      - promote

- name: Promote tag to Latest (Quay)
  pull: Always
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  resources:
    limits:
      cpu: 100
      memory: 256Mi
  commands:
  - n=0; while [ "$n" -lt 60 ] && [ ! "$(docker stats --no-stream)" ]; do n=$(( n + 1 )); sleep 1; done
  - docker login -u="ukhomeofficedigital+alpine" -p=$${DOCKER_TOKEN} quay.io
  - docker pull $${OCI_IMAGE_REPO}:$$(cat .alpine_version)
  - docker tag $${OCI_IMAGE_REPO}:$$(cat .alpine_version) $${OCI_IMAGE_REPO}:latest
  - docker push $${OCI_IMAGE_REPO}:latest
  environment:
    DOCKER_TOKEN:
      from_secret: DOCKER_TOKEN
  when:
    ref:
    - refs/tags/**
    event:
    - promote

- name: scan-image
  pull: Always
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/trivy/client:latest
  resources:
    limits:
      cpu: 1000
      memory: 1024Mi
  environment:
    IMAGE_NAME: quay.io/ukhomeofficedigital/alpine:${DRONE_COMMIT_SHA}
  when:
    event:
    - pull_request
    - push

- name: Push image tag to quay
  pull: Always
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  resources:
    limits:
      cpu: 100
      memory: 256Mi
  commands:
  - docker login -u="ukhomeofficedigital+alpine" -p=$${DOCKER_TOKEN} quay.io
  - docker push $${OCI_IMAGE_REPO}:$$(cat .alpine_version)
  - docker push $${OCI_IMAGE_REPO}:${DRONE_COMMIT_SHA}
  environment:
    DOCKER_TOKEN:
      from_secret: DOCKER_TOKEN
  when:
    branch:
    - master
    event:
      include:
      - push
      exclude:
      - promote

- name: Push Semver and Tag Repo - force
  pull: Always
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/acp-ci-tools
  resources:
    limits:
      cpu: 100
      memory: 256Mi
  commands:
  - git tag -a $(cat .alpine_version) -m "[CI SKIP] - alpine tag - $(cat .alpine_version)"
  - git push -f --tags
  when:
    branch:
    - master
    event:
    - push

services:
- name: docker
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  resources:
    limits:
      cpu: 1000
      memory: 1024Mi
