---
# IMPORTANT: only .drone.yml or .drone.star is needed
# By default, drone will look for .drone.yml which is expected to contain a yaml definition of the pipeline.
# It is also possible to define the pipeline in the Starlark language (see https://docs.bazel.build/versions/master/skylark/language.html)
# When using Starlark, you also need to configure the Drone repo settings and specify "Configuration" as .drone.star

kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: if-not-exists
  image: docker:19.03.12-dind
  commands:
  # wait for docker service to be up before running docker build
  - n=0; while [ "$n" -lt 60 ] && [ ! -e /var/run/docker.sock ]; do n=$(( n + 1 )); sleep 1; done
  - docker build -t alpine:$${DRONE_COMMIT_SHA} . --no-cache
  volumes:
  - name: dockersock
    path: /var/run
  when:
    event:
    - push
    - tag

- name: scan-image
  image: docker.digital.homeoffice.gov.uk/acp-anchore-submission:latest
  environment:
    IMAGE_NAME: alpine:${DRONE_COMMIT_SHA}
    SERVICE_URL: http://anchore-submission-server:10080
  when:
    event:
    - push
    - tag

- name: push_quay_tag
  pull: if-not-exists
  image: docker:19.03.12-dind
  commands:
  commands:
    - docker login -u="ukhomeofficedigital+alpine" -p=$${DOCKER_TOKEN} quay.io
    - docker tag alpine:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/alpine:$${DRONE_TAG}
    - docker tag alpine:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/alpine:latest
    - docker push quay.io/ukhomeofficedigital/alpine:$${DRONE_TAG}
  environment:
    DOCKER_TOKEN:
      from_secret: DOCKER_TOKEN
  volumes:
  - name: dockersock
    path: /var/run
  when:
    event:
    - tag

services:
- name: docker
  image: docker:19.03.12-dind
  volumes:
  - name: dockersock
    path: /var/run

- name: anchore-submission-server
  image: docker.digital.homeoffice.gov.uk/acp-anchore-submission:latest
  commands:
    - /anchore-submission server
  environment:
    ANCHORE_URL: "acp-anchore.acp.homeoffice.gov.uk"
    REGISTRY_URL: "acp-ephemeral-registry.acp.homeoffice.gov.uk"
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}

...